server:
  address: 0.0.0.0
  port: 8080
spring:
  kafka:
    bootstrap-servers: "192.168.1.222:9092"
    consumer:
      group-id: "skyCloud"
    streams: #1
      application-id: kafka-streams-demo #配置applictionId，也可使用spring.application.name代替
      properties:
        default:
          key:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde # key的序列化器(String)
          value:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde # value的序列化器(String)
